### ISSUE TITLE
Animating stroke-dasharray

### ISSUE THREAD

**Issue by domonique-ncino** [svgdotjs/svg.js#698]
There's not a smooth transition when trying to animate a stroke-dasharray attribute.
```css
@keyframes dash{
  0%{
    stroke-dasharray: 1,200;
    stroke-dashoffset: 0;
  }

  100%{
    stroke-dasharray: 214,270;
    stroke-dashoffset: 25;
  }
}
```

Works in CSS
```js
circle.attr({
  cx: frame.x / 2,
  cy: frame.y / 2,
  'fill-opacity': 0,
  stroke: '#fff',
  'stroke-width': 2,
  'stroke-dasharray': [10, 10],
  'stroke-dashoffset': 0,
  'stroke-linecap': 'round'
});

circle.animate(2000, '<>', 0).attr({
  'stroke-dasharray': [1, 1],
  'stroke-dashoffset': 0
}).rotate(360);
```
Not as smooth
